---
- 
  hosts: localhost
  connection: local
  sudo: True

  tasks:
    - name: Install ufw
      portage: package=net-firewall/ufw state=present
    - name: ufw - enable ssh
      ufw: rule=allow direction=in proto=tcp port=ssh
    - name: ufw - rate limit ssh
      ufw: rule=limit port=ssh proto=tcp
