---
- 
  hosts: localhost
  connection: local
  sudo: True

  tasks:
    - include: common-ufw.yml
    - include: common-packages.yml
    - include: common-services.yml

  hosts: buildhosts
  connection: local
  sudo: True
  tasks:
    - include: buildhost-packages.yml
